# Generated by Django 2.1 on 2019-04-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190414_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
