# Generated by Django 2.1 on 2019-04-29 04:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190429_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='xxxxxxxxxxxxxxxxxx'),
        ),
    ]
